[package]
name = "tachyon-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tachyon-core = { workspace = true }
tachyon-protocol = { workspace = true }
tachyon-store = { workspace = true }
tachyon-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
