[package]
name = "tachyon-judgment"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tachyon-models = { version = "0.0.1", path = "../tachyon-models" }
tachyon-router = { version = "0.0.1", path = "../tachyon-router" }
tachyon-telemetry = { version = "0.0.1", path = "../tachyon-telemetry" }
tachyon-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[features]
openjev = []

[lints]
workspace = true
