[package]
name = "tachyon-verify"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
blake3 = { workspace = true }
async-trait = { workspace = true }
tachyon-ir = { workspace = true }
tachyon-scheduler = { path = "../tachyon-scheduler" }
tachyon-tools = { path = "../tachyon-tools" }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tachyon-types = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tachyon-policy = { path = "../tachyon-policy" }

[lints]
workspace = true
