[package]
name = "tachyon-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
blake3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tachyon-policy = { version = "0.0.1", path = "../tachyon-policy" }
tachyon-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
walkdir = { workspace = true }
zstd = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lints]
workspace = true
